### ISSUE TITLE
requestFundamentalSummary(1, 50, 2024-12-19) -> CSVMappingException: Error mapping at index 44 with offset 0 with index name LastSplitDate

### ISSUE THREAD

**Issue by subes** [Petersoj/IQFeed4j#13]
Happened today (2024-12-21) when calling MarketSummaryFeed.requestFundamentalSummary(1, 50, 2024-12-19)

This iqfeed response (extracted from debugger): 
`[1, LM, C.BUI, "BUHLER INDUSTRIES INC", 20.5, 0, 7.32, 0, 0.15, 20071015, 20070921, 0.1, , , 3, 13, 0, , 56.75, 50, , , , , 2.44, , , , , , , , , , 2.95, 20241118, 1.97, 20240704, 2.95, 20241118, 1.97, 20240704, , 0, 99999999, 0, 99999999, 0, ]`

Causes this exception:
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMappingException: Error mapping at index 44 with offset 0 with index name LastSplitDate
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.downloadFundamentalSummary(FundamentalSnapshots.java:236)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.access$0(FundamentalSnapshots.java:218)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots$CachedDownloadFundamentalSummaryRequest.download(FundamentalSnapshots.java:389)
	at de.invesdwin.context.integration.network.request.ACachedMarshalledDownloadListRequest.call(ACachedMarshalledDownloadListRequest.java:43)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalSummary(FundamentalSnapshots.java:215)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalSnapshot(FundamentalSnapshots.java:202)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalSnapshot(FundamentalSnapshots.java:176)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalDataFromSnapshot(FundamentalSnapshots.java:46)
	at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedInstrumentSubscription.requestFundamentalData(IqfeedInstrumentSubscription.java:441)
	at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedInstrumentSubscription.getFundamentalData(IqfeedInstrumentSubscription.java:397)
	at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedSession.getInstrumentSubscription(IqfeedSession.java:437)
	at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableInstrumentsFromDownload(AIqfeedInstruments.java:118)
	at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableInstruments(AIqfeedInstruments.java:75)
	at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableSymbols(AIqfeedInstruments.java:161)
	at de.invesdwin.trading.iqfeed.trades.run.internal.IqfeedTradesLiveRun.run(IqfeedTradesLiveRun.java:48)
	at de.invesdwin.trading.iqfeed.trades.run.IqfeedTradesRunFactory.run(IqfeedTradesRunFactory.java:23)
	at de.invesdwin.trading.financialdata.live.source.iqfeed.trades.IqfeedTradesFinancialdataLiveSourceService.runStrategy_aroundBody0(IqfeedTradesFinancialdataLiveSourceService.java:171)
	at de.invesdwin.trading.financialdata.live.source.iqfeed.trades.IqfeedTradesFinancialdataLiveSourceService$AjcClosure1.run(IqfeedTradesFinancialdataLiveSourceService.java:1)
	at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect.ajc$around$org_springframework_scheduling_aspectj_AbstractAsyncExecutionAspect$1$6c004c3eproceed(AbstractAsyncExecutionAspect.aj:65)
	at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect$AbstractAsyncExecutionAspect$1.call(AbstractAsyncExecutionAspect.aj:76)
	at de.invesdwin.util.concurrent.internal.WrappedCallable.call(WrappedCallable.java:59)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at de.invesdwin.util.concurrent.internal.WrappedThreadFactory.lambda$0(WrappedThreadFactory.java:49)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.ExecutionException: net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMappingException: Error mapping at index 44 with offset 0 with index name LastSplitDate
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at net.jacobpeterson.iqfeed4j.feed.message.MultiMessageAccumulator.getMessages(MultiMessageAccumulator.java:50)
	at net.jacobpeterson.iqfeed4j.feed.lookup.marketsummary.MarketSummaryFeed.requestFundamentalSummary(MarketSummaryFeed.java:418)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.downloadFundamentalSummary(FundamentalSnapshots.java:223)
	... 28 more
Caused by: net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMappingException: Error mapping at index 44 with offset 0 with index name LastSplitDate
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.map.NamedCSVMapper.map(NamedCSVMapper.java:89)
	at net.jacobpeterson.iqfeed4j.feed.lookup.marketsummary.MarketSummaryFeed.handleMultiMessage(MarketSummaryFeed.java:285)
	at net.jacobpeterson.iqfeed4j.feed.lookup.marketsummary.MarketSummaryFeed.onMessageReceived(MarketSummaryFeed.java:213)
	at net.jacobpeterson.iqfeed4j.feed.AbstractFeed.run(AbstractFeed.java:184)
	... 1 more
Caused by: java.time.format.DateTimeParseException: Text '99999999' could not be parsed: Invalid value for MonthOfYear (valid values 1 - 12): 99
	at java.base/java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:2023)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1958)
	at java.base/java.time.LocalDate.parse(LocalDate.java:430)
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.AbstractCSVMapper$DateTimeConverters.lambda$static$1(AbstractCSVMapper.java:97)
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMapping.lambda$new$0(CSVMapping.java:25)
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMapping.apply(CSVMapping.java:46)
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.map.NamedCSVMapper.map(NamedCSVMapper.java:86)
	... 4 more
Caused by: java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 99
	at java.base/java.time.temporal.ValueRange.checkValidIntValue(ValueRange.java:338)
	at java.base/java.time.temporal.ChronoField.checkValidIntValue(ChronoField.java:737)
	at java.base/java.time.chrono.IsoChronology.resolveYMD(IsoChronology.java:644)
	at java.base/java.time.chrono.IsoChronology.resolveYMD(IsoChronology.java:126)
	at java.base/java.time.chrono.AbstractChronology.resolveDate(AbstractChronology.java:442)
	at java.base/java.time.chrono.IsoChronology.resolveDate(IsoChronology.java:586)
	at java.base/java.time.chrono.IsoChronology.resolveDate(IsoChronology.java:126)
	at java.base/java.time.format.Parsed.resolveDateFields(Parsed.java:366)
	at java.base/java.time.format.Parsed.resolveFields(Parsed.java:272)
	at java.base/java.time.format.Parsed.resolve(Parsed.java:259)
	at java.base/java.time.format.DateTimeParseContext.toResolved(DateTimeParseContext.java:331)
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2058)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	... 9 more
java.lang.RuntimeException: java.util.concurrent.ExecutionException: net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMappingException: Error mapping at index 44 with offset 0 with index name LastSplitDate
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.downloadFundamentalSummary(FundamentalSnapshots.java:236)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.access$0(FundamentalSnapshots.java:218)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots$CachedDownloadFundamentalSummaryRequest.download(FundamentalSnapshots.java:389)
	at de.invesdwin.context.integration.network.request.ACachedMarshalledDownloadListRequest.call(ACachedMarshalledDownloadListRequest.java:43)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalSummary(FundamentalSnapshots.java:215)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalSnapshot(FundamentalSnapshots.java:202)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalSnapshot(FundamentalSnapshots.java:176)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalDataFromSnapshot(FundamentalSnapshots.java:46)
	at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedInstrumentSubscription.requestFundamentalData(IqfeedInstrumentSubscription.java:441)
	at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedInstrumentSubscription.getFundamentalData(IqfeedInstrumentSubscription.java:397)
	at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedSession.getInstrumentSubscription(IqfeedSession.java:437)
	at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableInstrumentsFromDownload(AIqfeedInstruments.java:118)
	at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableInstruments(AIqfeedInstruments.java:75)
	at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableSymbols(AIqfeedInstruments.java:161)
	at de.invesdwin.trading.iqfeed.trades.run.internal.IqfeedTradesLiveRun.run(IqfeedTradesLiveRun.java:48)
	at de.invesdwin.trading.iqfeed.trades.run.IqfeedTradesRunFactory.run(IqfeedTradesRunFactory.java:23)
	at de.invesdwin.trading.financialdata.live.source.iqfeed.trades.IqfeedTradesFinancialdataLiveSourceService.runStrategy_aroundBody0(IqfeedTradesFinancialdataLiveSourceService.java:171)
	at de.invesdwin.trading.financialdata.live.source.iqfeed.trades.IqfeedTradesFinancialdataLiveSourceService$AjcClosure1.run(IqfeedTradesFinancialdataLiveSourceService.java:1)
	at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect.ajc$around$org_springframework_scheduling_aspectj_AbstractAsyncExecutionAspect$1$6c004c3eproceed(AbstractAsyncExecutionAspect.aj:65)
	at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect$AbstractAsyncExecutionAspect$1.call(AbstractAsyncExecutionAspect.aj:76)
	at de.invesdwin.util.concurrent.internal.WrappedCallable.call(WrappedCallable.java:59)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at de.invesdwin.util.concurrent.internal.WrappedThreadFactory.lambda$0(WrappedThreadFactory.java:49)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.ExecutionException: net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMappingException: Error mapping at index 44 with offset 0 with index name LastSplitDate
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at net.jacobpeterson.iqfeed4j.feed.message.MultiMessageAccumulator.getMessages(MultiMessageAccumulator.java:50)
	at net.jacobpeterson.iqfeed4j.feed.lookup.marketsummary.MarketSummaryFeed.requestFundamentalSummary(MarketSummaryFeed.java:418)
	at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.downloadFundamentalSummary(FundamentalSnapshots.java:223)
	... 28 more
Caused by: net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMappingException: Error mapping at index 44 with offset 0 with index name LastSplitDate
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.map.NamedCSVMapper.map(NamedCSVMapper.java:89)
	at net.jacobpeterson.iqfeed4j.feed.lookup.marketsummary.MarketSummaryFeed.handleMultiMessage(MarketSummaryFeed.java:285)
	at net.jacobpeterson.iqfeed4j.feed.lookup.marketsummary.MarketSummaryFeed.onMessageReceived(MarketSummaryFeed.java:213)
	at net.jacobpeterson.iqfeed4j.feed.AbstractFeed.run(AbstractFeed.java:184)
	... 1 more
Caused by: java.time.format.DateTimeParseException: Text '99999999' could not be parsed: Invalid value for MonthOfYear (valid values 1 - 12): 99
	at java.base/java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:2023)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1958)
	at java.base/java.time.LocalDate.parse(LocalDate.java:430)
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.AbstractCSVMapper$DateTimeConverters.lambda$static$1(AbstractCSVMapper.java:97)
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMapping.lambda$new$0(CSVMapping.java:25)
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMapping.apply(CSVMapping.java:46)
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.map.NamedCSVMapper.map(NamedCSVMapper.java:86)
	... 4 more
Caused by: java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 99
	at java.base/java.time.temporal.ValueRange.checkValidIntValue(ValueRange.java:338)
	at java.base/java.time.temporal.ChronoField.checkValidIntValue(ChronoField.java:737)
	at java.base/java.time.chrono.IsoChronology.resolveYMD(IsoChronology.java:644)
	at java.base/java.time.chrono.IsoChronology.resolveYMD(IsoChronology.java:126)
	at java.base/java.time.chrono.AbstractChronology.resolveDate(AbstractChronology.java:442)
	at java.base/java.time.chrono.IsoChronology.resolveDate(IsoChronology.java:586)
	at java.base/java.time.chrono.IsoChronology.resolveDate(IsoChronology.java:126)
	at java.base/java.time.format.Parsed.resolveDateFields(Parsed.java:366)
	at java.base/java.time.format.Parsed.resolveFields(Parsed.java:272)
	at java.base/java.time.format.Parsed.resolve(Parsed.java:259)
	at java.base/java.time.format.DateTimeParseContext.toResolved(DateTimeParseContext.java:331)
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2058)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	... 9 more
```

**Comment by subes** [comment]
getFundamentalSummary(36, 154, 2024-12-19T00:00:00.000)

causes

```
de.invesdwin.context.log.error.LoggedRuntimeException: #00000001 de.invesdwin.trading.broker.instrument.InstrumentSubscriptionFailedException: getFundamentalData:java.util.concurrent.ExecutionException: net.jacobpeterson.iqfeed4j.feed.exception.IQFeedRuntimeException: 0,Bad line in file.  Expected 47 fields.  Received 48.  First field contains: CAPESIZE.
        ... 24 omitted, see following cause or error.log
Caused by - de.invesdwin.trading.broker.instrument.InstrumentSubscriptionFailedException: getFundamentalData:java.util.concurrent.ExecutionException: net.jacobpeterson.iqfeed4j.feed.exception.IQFeedRuntimeException: 0,Bad line in file.  Expected 47 fields.  Received 48.  First field contains: CAPESIZE.
      * at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedInstrumentSubscription.handleSubscribedException(IqfeedInstrumentSubscription.java:336) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedInstrumentSubscription.getFundamentalData(IqfeedInstrumentSubscription.java:400) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedSession.getInstrumentSubscription(IqfeedSession.java:442) *
      * at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableInstrumentsFromDownload(AIqfeedInstruments.java:118) *
      * at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableInstruments(AIqfeedInstruments.java:75) *
      * at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableSymbols(AIqfeedInstruments.java:161) *
      * at de.invesdwin.trading.iqfeed.trades.run.internal.IqfeedTradesLiveRun.run(IqfeedTradesLiveRun.java:48) *
      * at de.invesdwin.trading.iqfeed.trades.run.IqfeedTradesRunFactory.run(IqfeedTradesRunFactory.java:23) *
      * at de.invesdwin.trading.financialdata.live.source.iqfeed.trades.IqfeedTradesFinancialdataLiveSourceService.runStrategy_aroundBody0(IqfeedTradesFinancialdataLiveSourceService.java:171) *
      * at de.invesdwin.trading.financialdata.live.source.iqfeed.trades.IqfeedTradesFinancialdataLiveSourceService$AjcClosure1.run(IqfeedTradesFinancialdataLiveSourceService.java:1) *
        at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect.ajc$around$org_springframework_scheduling_aspectj_AbstractAsyncExecutionAspect$1$6c004c3eproceed(AbstractAsyncExecutionAspect.aj:65)
        at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect$AbstractAsyncExecutionAspect$1.call(AbstractAsyncExecutionAspect.aj:76)
      * at de.invesdwin.util.concurrent.internal.WrappedCallable.call(WrappedCallable.java:59) *
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      * at de.invesdwin.util.concurrent.internal.WrappedThreadFactory.lambda$0(WrappedThreadFactory.java:49) *
        ... 2 more, see error.log
Caused by - java.util.concurrent.ExecutionException: net.jacobpeterson.iqfeed4j.feed.exception.IQFeedRuntimeException: 0,Bad line in file.  Expected 47 fields.  Received 48.  First field contains: CAPESIZE.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
      * at de.invesdwin.trading.iqfeed.iqfeed4j.glue.TimeoutMultiMessageAccumulator.getMessages(TimeoutMultiMessageAccumulator.java:46) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedSession$13.callRetry(IqfeedSession.java:1225) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedSession$13.callRetry(IqfeedSession.java:1) *
      * at de.invesdwin.context.integration.retry.task.ARetryCallable$1.call(ARetryCallable.java:27) *
      * at de.invesdwin.context.integration.retry.internal.ExceptionCauseRetryCallback.doWithRetry(ExceptionCauseRetryCallback.java:47) *
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:344)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:217)
      * at de.invesdwin.context.integration.retry.task.ARetryCallable.call(ARetryCallable.java:35) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedSession.getFundamentalSummary(IqfeedSession.java:1270) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots$CachedDownloadFundamentalSummaryRequest.download(FundamentalSnapshots.java:362) *
      * at de.invesdwin.context.integration.network.request.ACachedMarshalledDownloadListRequest.call(ACachedMarshalledDownloadListRequest.java:43) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalSummary(FundamentalSnapshots.java:210) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalSnapshot(FundamentalSnapshots.java:197) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalSnapshot(FundamentalSnapshots.java:171) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.glue.FundamentalSnapshots.getFundamentalDataFromSnapshot(FundamentalSnapshots.java:41) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedInstrumentSubscription.requestFundamentalData(IqfeedInstrumentSubscription.java:441) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedInstrumentSubscription.getFundamentalData(IqfeedInstrumentSubscription.java:397) *
      * at de.invesdwin.trading.iqfeed.iqfeed4j.IqfeedSession.getInstrumentSubscription(IqfeedSession.java:442) *
      * at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableInstrumentsFromDownload(AIqfeedInstruments.java:118) *
      * at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableInstruments(AIqfeedInstruments.java:75) *
      * at de.invesdwin.trading.iqfeed.AIqfeedInstruments.getAvailableSymbols(AIqfeedInstruments.java:161) *
      * at de.invesdwin.trading.iqfeed.trades.run.internal.IqfeedTradesLiveRun.run(IqfeedTradesLiveRun.java:48) *
      * at de.invesdwin.trading.iqfeed.trades.run.IqfeedTradesRunFactory.run(IqfeedTradesRunFactory.java:23) *
      * at de.invesdwin.trading.financialdata.live.source.iqfeed.trades.IqfeedTradesFinancialdataLiveSourceService.runStrategy_aroundBody0(IqfeedTradesFinancialdataLiveSourceService.java:171) *
      * at de.invesdwin.trading.financialdata.live.source.iqfeed.trades.IqfeedTradesFinancialdataLiveSourceService$AjcClosure1.run(IqfeedTradesFinancialdataLiveSourceService.java:1) *
        at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect.ajc$around$org_springframework_scheduling_aspectj_AbstractAsyncExecutionAspect$1$6c004c3eproceed(AbstractAsyncExecutionAspect.aj:65)
        at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect$AbstractAsyncExecutionAspect$1.call(AbstractAsyncExecutionAspect.aj:76)
      * at de.invesdwin.util.concurrent.internal.WrappedCallable.call(WrappedCallable.java:59) *
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      * at de.invesdwin.util.concurrent.internal.WrappedThreadFactory.lambda$0(WrappedThreadFactory.java:49) *
        ... 2 more, see error.log
Caused by - net.jacobpeterson.iqfeed4j.feed.exception.IQFeedRuntimeException: 0,Bad line in file.  Expected 47 fields.  Received 48.  First field contains: CAPESIZE.
        ... 4 more, see error.log
```
