### ISSUE TITLE
Error while fetching monthly Bars

### ISSUE THREAD

**Issue by SriniKancharla** [Petersoj/IQFeed4j#3]
For input string: "2165667000""

net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMapping.lambda$new$0(CSVMapping.java:25)

**Comment by Petersoj** [comment]
Could you provide the code snippet that you used that resulted in this error?

**Comment by SriniKancharla** [comment]
I tried to request Monthly historical data for QQQ and SPY and got this error:

Here is the call:
            List<DatedInterval> dataIntervals = iqFeed4j.historical().requestMonthIntervals(ticker, maxDataPoints, 
                    DataDirection.OLDEST_TO_NEWEST, PartialDatapoint.INCLUDE);

Here is the stack trace

2021-10-23 07:53:30.184  INFO 4244 --- [           main] c.s.i.IqDataFetcherApplication           : Started IqDataFetcherApplication in 1.795 seconds (JVM running for 2.719)
java.util.concurrent.ExecutionException: net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMappingException: Error mapping at index 5 with offset 2!
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at net.jacobpeterson.iqfeed4j.feed.message.MultiMessageAccumulator.getMessages(MultiMessageAccumulator.java:52)
	at net.jacobpeterson.iqfeed4j.feed.lookup.historical.HistoricalFeed.requestMonthIntervals(HistoricalFeed.java:909)
Disconnected from the target VM, address: '127.0.0.1:58050', transport: 'socket'
	at com.sk.iqDataFetcher.history.MonDataFetcherService.getHistoryBarsCollect(MonDataFetcherService.java:77)
	at com.sk.iqDataFetcher.history.MonDataFetcherService.getMonthlyHistory(MonDataFetcherService.java:48)
	at com.sk.iqDataFetcher.IqDataFetcherApplication.run(IqDataFetcherApplication.java:54)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.sk.iqDataFetcher.IqDataFetcherApplication.main(IqDataFetcherApplication.java:59)
Caused by: net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMappingException: Error mapping at index 5 with offset 2!
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.index.IndexCSVMapper.map(IndexCSVMapper.java:130)
	at net.jacobpeterson.iqfeed4j.feed.lookup.AbstractLookupFeed.handleStandardMultiMessage(AbstractLookupFeed.java:93)
	at net.jacobpeterson.iqfeed4j.feed.lookup.historical.HistoricalFeed.onMessageReceived(HistoricalFeed.java:138)
	at net.jacobpeterson.iqfeed4j.feed.AbstractFeed.run(AbstractFeed.java:232)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NumberFormatException: For input string: "2165667000"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMapping.lambda$new$0(CSVMapping.java:25)
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.CSVMapping.apply(CSVMapping.java:46)
	at net.jacobpeterson.iqfeed4j.util.csv.mapper.index.IndexCSVMapper.map(IndexCSVMapper.java:128)

**Comment by Petersoj** [comment]
The `NumberFormatException` being thrown is due to integer overflow when mapping large integer fields (integers that are greater than `Integer.MAX_VALUE`). It appears in this case that the period volume for a monthly `DatedInterval` is very large, especially for tickers like `QQQ` and `SPY`. They're so large that they don't fit within a 32-bit integer. So, I've changed all volume-related fields in historical lookup objects so that they are of type `Long` instead of `Integer`. These fixes are reflected in release [`6.2-1.5.3`](https://github.com/Petersoj/IQFeed4j/releases/tag/6.2-1.5.3). Thanks for reporting this!

**Comment by SriniKancharla** [comment]
Thank you so much for fixing it so quickly.
