### ISSUE TITLE
Init Exception

### ISSUE THREAD

**Issue by SriniKancharla** [Petersoj/IQFeed4j#4]
I get the following exception while initilizing the bean iqFeed4j

Caused by: java.lang.ExceptionInInitializerError: null
        at net.jacobpeterson.iqfeed4j.IQFeed4j.<init>(IQFeed4j.java:59) ~[iqfeed4j-6.2-1.5.3.jar!/:na]
        at com.srini.iqDataFetcher.IqDataFetcherApplication.iqFeed4jSingleton(IqDataFetcherApplication.java:38) ~[classes!/:1.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.10.jar!/:5.3.10]
        ... 27 common frames omitted
Caused by: java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:614) ~[na:na]
        at java.base/java.lang.Integer.parseInt(Integer.java:770) ~[na:na]
        at net.jacobpeterson.iqfeed4j.properties.IQFeed4jProperties.<clinit>(IQFeed4jProperties.java:73) ~[iqfeed4j-6.2-1.5.3.jar!/:na]
        ... 34 common frames omitted

**Comment by SriniKancharla** [comment]
When I do it manually I get the following error

java.lang.NoClassDefFoundError: Could not initialize class net.jacobpeterson.iqfeed4j.properties.IQFeed4jProperties
        at net.jacobpeterson.iqfeed4j.IQFeed4j.<init>(IQFeed4j.java:59) ~[iqfeed4j-6.2-1.5.3.jar!/:na]
        at com.srini.iqDataFetcher.history.IQFeed.getInstance(IQFeed.java:13) ~[classes!/:1.0]
        at com.srini.iqDataFetcher.history.DataFetcherService.getHistoryMinBarsCollect(DataFetcherService.java:108) ~[classes!/:1.0]
        at com.srini.iqDataFetcher.history.DataFetcherService.getMinHistory(DataFetcherService.java:59) ~[classes!/:1.0]
        at com.srini.iqDataFetcher.IqDataFetcherApplication.fetchMinIndex(IqDataFetcherApplication.java:83) ~[classes!/:1.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.10.jar!/:5.3.10]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.10.jar!/:5.3.10]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.10.jar!/:5.3.10]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by SriniKancharla** [comment]
Properties are not read correctly even though iqfeed4j.properties is in classpath

2021-10-27 11:01:02.065  WARN 13320 --- [   scheduling-1] n.j.i.util.properties.PropertyUtil       : No default property file found for: iqfeed4j.properties
2021-10-27 11:01:02.071 ERROR 13320 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.ExceptionInInitializerError: null
        at net.jacobpeterson.iqfeed4j.IQFeed4j.<init>(IQFeed4j.java:59) ~[iqfeed4j-6.2-1.5.3.jar!/:na]
        at com.srini.iqDataFetcher.IQFeed4jWrapper.getInstance(IQFeed4jWrapper.java:28) ~[classes!/:1.0]
        at com.srini.iqDataFetcher.history.DataFetcherService.getHistoryMinBarsCollect(DataFetcherService.java:103) ~[classes!/:1.0]
        at com.srini.iqDataFetcher.history.DataFetcherService.getMinHistory(DataFetcherService.java:54) ~[classes!/:1.0]
        at com.srini.iqDataFetcher.IqDataFetcherApplication.fetchMinIndex(IqDataFetcherApplication.java:81) ~[classes!/:1.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.10.jar!/:5.3.10]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.10.jar!/:5.3.10]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.10.jar!/:5.3.10]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:614) ~[na:na]
        at java.base/java.lang.Integer.parseInt(Integer.java:770) ~[na:na]
        at net.jacobpeterson.iqfeed4j.properties.IQFeed4jProperties.<clinit>(IQFeed4jProperties.java:73) ~[iqfeed4j-6.2-1.5.3.jar!/:na]
        ... 18 common frames omitted

**Comment by Petersoj** [comment]
I believe this is a similar issue that I had in another one of my open-source APIs here: https://github.com/Petersoj/alpaca-java/pull/100. Spring's class loader doesn't put `iqfeed4j.default.properties` on the system class loader's classpath (e.g. `ClassLoader.getSystemClassLoader()`), but it exists on the `PropertyUtil` class loader classpath. I'm not sure why that's the case for Spring boot, but I believe that's why you're getting those `ExceptionInInitializerErrors` due to NPEs from the default property file not being loaded. I've just released version [`6.2-1.5.4`](https://github.com/Petersoj/IQFeed4j/releases/tag/6.2-1.5.4) which hopefully fixes this error. Give it a try and let me know if it works.

**Comment by SriniKancharla** [comment]
Thanks. That fixed the issue.
